### ISSUE TITLE
BinderHub trying to lookup wrong Kubernetes namespace

### ISSUE THREAD

**Issue by iwilltry42** [jupyterhub/binderhub#1075]
Hi,

I just deployed BinderHub onto our Kubernetes cluster, setting the env var `BUILD_NAMESPACE=jupyter`.
Still, it doesn't start correctly and apparently tries to lookup resources in the `default` namespace instead of the release namespace `jupyter`.

Here's the error:
```
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods is forbidden: User \"system:serviceaccount:jupyter:binderhub\" cannot list resource \"pods\" in API group \"\" in the namespace \"default\"","reason":"Forbidden","details":{"kind":"pods"},"code":403}
```

And here's the relevant log leading up to that error:
```
[E 200323 10:44:47 app:688] Failed to cleanup build pods
    Traceback (most recent call last):
      File "/usr/local/lib/python3.7/site-packages/binderhub/app.py", line 680, in watch_build_pods
        lambda: Build.cleanup_builds(
      File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/usr/local/lib/python3.7/site-packages/binderhub/app.py", line 683, in <lambda>
        self.build_max_age,
      File "/usr/local/lib/python3.7/site-packages/binderhub/build.py", line 97, in cleanup_builds
        label_selector='component=binderhub-build',
      File "/usr/local/lib/python3.7/site-packages/kubernetes/client/apis/core_v1_api.py", line 12469, in list_namespaced_pod
        (data) = self.list_namespaced_pod_with_http_info(namespace, **kwargs)
      File "/usr/local/lib/python3.7/site-packages/kubernetes/client/apis/core_v1_api.py", line 12572, in list_namespaced_pod_with_http_info
        collection_formats=collection_formats)
      File "/usr/local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 334, in call_api
        _return_http_data_only, collection_formats, _preload_content, _request_timeout)
      File "/usr/local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 168, in __call_api
        _request_timeout=_request_timeout)
      File "/usr/local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 355, in request
        headers=headers)
      File "/usr/local/lib/python3.7/site-packages/kubernetes/client/rest.py", line 231, in GET
        query_params=query_params)
      File "/usr/local/lib/python3.7/site-packages/kubernetes/client/rest.py", line 222, in request
        raise ApiException(http_resp=r)
    kubernetes.client.rest.ApiException: (403)
    Reason: Forbidden
    HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'Date': 'Mon, 23 Mar 2020 10:44:47 GMT', 'Content-Length': '284'})
    HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods is forbidden: User \"system:serviceaccount:jupyter:binderhub\" cannot list resource \"pods\" in API group \"\" in the namespace \"default\"","reason":"Forbidden","details":{"kind":"pods"},"code":403}
```

**Comment by manics** [comment]
Hi. Would you mind sharing your full configuration, with secrets redacted? It'll also be helpful if you could share the helm command you used to deploy it. Thanks!

**Comment by iwilltry42** [comment]
@manics Sure thing.
`helm upgrade --install jupyter jupyter -f myvalues.yaml``(I have fetched/extracted the helm chart in the jupyter folder.

Here's the values file (note: I use binderhub as a subchart):
```
pdb:
    enabled: true
    minAvailable: 1

  replicas: 1

  resources:
    requests:
      cpu: 0.2
      memory: 512Mi

  rbac:
    enabled: true

  nodeSelector: {}

  image:
    name: jupyterhub/k8s-binderhub
    tag: '0.2.0-n132.h1a8ce62'

  # registry here is only used to create docker config.json
  registry:
    # key in 'auths' in docker config.json,
    # ~always the registry url
    url: <myreg>
    # registry username+password
    username: <user>
    password: <pw>

  service:
    type: ClusterIP
    labels: {}
    annotations:
      prometheus.io/scrape: 'true'
    nodePort:

  config:
    BinderHub:
      hub:
        apiToken: &bindertoken <TOKEN>
        url: http://jupyterhub.ds.trv.cloud
      use_registry: true
      image_prefix: <myreg>/binder/binder-

  extraConfig: {}

  # have to set cors.allowOrigin twice:
  # once in top-level cors.allowOrigin,
  # and again in jupyterhub.hub.extraConfigMap.cors.allowOrigin

  # Using YAML anchors, `&cors` for the first appearance and `*cors` for subsequent
  # appearances, allows us to remove redundancy in this (BinderHub) `values.yaml`.
  # The anchors do not extend beyond this file.
  # As such, users must set `cors` separately for their own user `values.yaml` for notebooks.
  # `cors` will be set separately in the user `values.yaml` and binderhub`values.yaml`.
  # The same anchor pattern (`&cors`, `*cors`) can be used in the user `values.yaml`.

  cors: &cors
    allowOrigin:

  deployment:
    labels: {}

  dind:
    enabled: false
    initContainers: []
    daemonset:
      image:
        name: docker
        tag: 19.03.5-dind
      # Additional command line arguments to pass to dockerd
      extraArgs: []
    storageDriver: overlay2
    resources: {}
    hostSocketDir: /var/run/dind
    hostLibDir: /var/lib/dind

  imageCleaner:
    enabled: true
    image:
      name: jupyterhub/k8s-image-cleaner
      tag: '0.2.0-n096.h4e521a1'
      repository: jupyterhub/k8s-image-cleaner
    # delete an image at most every 5 seconds
    delay: 5
    # Interpret threshold values as percentage or bytes
    imageGCThresholdType: "relative"
    # when 80% of inodes are used,
    # cull images until it drops below 60%
    imageGCThresholdHigh: 80
    imageGCThresholdLow: 60
    # cull images on the host docker as well as dind
    host:
      enabled: true
      dockerSocket: /var/run/docker.sock
      dockerLibDir: /var/lib/docker

  ingress:
    enabled: true
    https:
      enabled: false
      type: kube-lego
    hosts:
      - binderhub.ds.trv.cloud
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    tls: []
      # Secrets must be manually created in the namespace.
      # - secretName: chart-example-tls
      #   hosts:
      #     - chart-example.local

  initContainers: []
  extraVolumes: []
  extraVolumeMounts: []
  extraEnv: []
```

I exec'd into the pod and could see that it has `BUILD_NAMESPACE=jupyter` set in the environment.
Not sure where I can find the final configuration, but I can see that it should take this env var in the `bidnerhub_config.py`:
```
if os.getenv('BUILD_NAMESPACE'):
    c.BinderHub.build_namespace = os.environ['BUILD_NAMESPACE']
```

**Comment by iwilltry42** [comment]
Nevermind, it seems like I had a mistake in my configuration and thus it didn't apply the config at all. I would have expected a fatal error here that exits, but it just kept on running.
I fixed the config parameters in my values and now it's working again :+1:
