### ISSUE TITLE
Read the docs HTML build failure

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/binderhub#1173]
The HTML build is failing. I want to focus right now on bumping README badges for travis.org -> .com migration but the thing to do I think is:

1. Start using a readthedocs configuration like in z2jh, of v2 kind, name it .readthedocs.yml for aesthetics while we are at it.
2. Make sphinx be >=2 in dependencies I think, depends on stuff installed. See doc-requirements.txt of z2jh for notes relevant for understanding some parts about doc-requirements that are used on RTD.

**Comment by betatim** [comment]
What do you mean with RTD build is failing? https://github.com/jupyterhub/binderhub/pull/1172 was a recent build and it looks like the status of the RTD check was green :-/

**Comment by betatim** [comment]
Checked the build of `master` and that is indeed failing despite the PR working. Super confusing.

**Comment by betatim** [comment]
This is the full error:
```
Running Sphinx v3.2.1
loading translations [en]... done
making output directory... done
loading pickled environment... done
myst v0.12.10: MdParserConfig(renderer='sphinx', commonmark_only=False, dmath_enable=True, dmath_allow_labels=True, dmath_allow_space=True, dmath_allow_digits=True, amsmath_enable=False, deflist_enable=False, update_mathjax=True, admonition_enable=False, figure_enable=False, disable_syntax=[], html_img_enable=False, url_schemes=None, heading_anchors=None)
building [mo]: targets for 0 po files that are out of date
building [readthedocssinglehtmllocalmedia]: all documents
updating environment: 0 added, 0 changed, 0 removed
looking for now-outdated files... none found
preparing documents... done
assembling single document... zero-to-binderhub/index zero-to-binderhub/setup-prerequisites zero-to-binderhub/setup-registry zero-to-binderhub/setup-binderhub zero-to-binderhub/turn-off customization/index customizing debug authentication https developer/index overview eventlogging api developer/repoproviders reference/ref-index reference/app reference/build reference/builder reference/launcher reference/main reference/registry reference/repoproviders contribute done
writing... failed

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/binderhub/envs/latest/lib/python3.7/site-packages/sphinx/builders/html/__init__.py", line 1013, in handle_page
    output = self.templates.render(templatename, ctx)
  File "/home/docs/checkouts/readthedocs.org/user_builds/binderhub/envs/latest/lib/python3.7/site-packages/sphinx/jinja2glue.py", line 192, in render
    return self.environment.get_template(template).render(context)
  File "/home/docs/checkouts/readthedocs.org/user_builds/binderhub/envs/latest/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/docs/checkouts/readthedocs.org/user_builds/binderhub/envs/latest/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/docs/checkouts/readthedocs.org/user_builds/binderhub/envs/latest/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/docs/checkouts/readthedocs.org/user_builds/binderhub/envs/latest/lib/python3.7/site-packages/sphinx/themes/basic/page.html", line 10, in top-level template code
    {%- extends "layout.html" %}
  File "/home/docs/checkouts/readthedocs.org/user_builds/binderhub/envs/latest/lib/python3.7/site-packages/pydata_sphinx_theme/layout.html", line 10, in top-level template code
    <a class='right-next' id="next-link" href="{{ next.link|e }}" title="{{ _('next page')}}">{{ next_title or next.title }}</a>
  File "/home/docs/checkouts/readthedocs.org/user_builds/binderhub/envs/latest/lib/python3.7/site-packages/sphinx/themes/basic/../basic/layout.html", line 174, in top-level template code
    {%- block content %}
  File "/home/docs/checkouts/readthedocs.org/user_builds/binderhub/envs/latest/lib/python3.7/site-packages/pydata_sphinx_theme/layout.html", line 55, in block "content"
    {% block docs_toc %}
  File "/home/docs/checkouts/readthedocs.org/user_builds/binderhub/envs/latest/lib/python3.7/site-packages/pydata_sphinx_theme/layout.html", line 58, in block "docs_toc"
    {%- include "docs-toc.html" %}
  File "/home/docs/checkouts/readthedocs.org/user_builds/binderhub/envs/latest/lib/python3.7/site-packages/pydata_sphinx_theme/docs-toc.html", line 24, in top-level template code
    {% include "edit_this_page.html" %}
  File "/home/docs/checkouts/readthedocs.org/user_builds/binderhub/envs/latest/lib/python3.7/site-packages/pydata_sphinx_theme/edit_this_page.html", line 4, in top-level template code
    <a href="{{ get_edit_url() }}">
  File "/home/docs/checkouts/readthedocs.org/user_builds/binderhub/envs/latest/lib/python3.7/site-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/binderhub/envs/latest/lib/python3.7/site-packages/pydata_sphinx_theme/__init__.py", line 160, in get_edit_url
    file_name = f"{pagename}{context['page_source_suffix']}"
KeyError: 'page_source_suffix'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/binderhub/envs/latest/lib/python3.7/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/binderhub/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 348, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/binderhub/envs/latest/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 294, in build_update
    self.build(['__all__'], to_build)
  File "/home/docs/checkouts/readthedocs.org/user_builds/binderhub/envs/latest/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 361, in build
    self.write(docnames, list(updated_docnames), method)
  File "/home/docs/checkouts/readthedocs.org/user_builds/binderhub/envs/latest/lib/python3.7/site-packages/sphinx/builders/singlehtml.py", line 165, in write
    self.write_doc(self.config.master_doc, doctree)
  File "/home/docs/checkouts/readthedocs.org/user_builds/binderhub/envs/latest/lib/python3.7/site-packages/sphinx/builders/html/__init__.py", line 603, in write_doc
    self.handle_page(docname, ctx, event_arg=doctree)
  File "/home/docs/checkouts/readthedocs.org/user_builds/binderhub/envs/latest/lib/python3.7/site-packages/sphinx/builders/html/__init__.py", line 1021, in handle_page
    (pagename, exc)) from exc
sphinx.errors.ThemeError: An error happened in rendering the page index.
Reason: KeyError('page_source_suffix')

Theme error:
An error happened in rendering the page index.
Reason: KeyError('page_source_suffix')
```

On `master` we use `pydata-sphinx-theme-0.4.1` which is also the version that is installed during the PR. Looking at why it fails in one case but not the other

**Comment by betatim** [comment]
Looking at the last successful build of `master` on RTD and the first time it failed I could narrow it down to this diff: https://github.com/jupyterhub/binderhub/compare/7847789c7abf607d75960d90d087815512f0ba55...ddb603b50690b31477def3a55a17462237e6bdd7 @choldgraf could it be something about myst that breaks the setting of the `page_source_suffix` variable?

**Comment by consideRatio** [comment]
@betatim this is a tackled issue in other repos, I think I repeated the fix for this repo in #1177.

**Comment by choldgraf** [comment]
ah yeah I believe this was a pydata-sphinx-theme error that pops up when building single-page builds and should now be fixed, so we just need to bump to master of the pydata theme

**Comment by consideRatio** [comment]
![image](https://user-images.githubusercontent.com/3837114/97602588-c6f77280-1a0b-11eb-9454-1b06cb7af957.png)

Success!
