### ISSUE TITLE
Failed to connect to event stream. RuntimeError: No space left on device: 'cache'

### ISSUE THREAD

**Issue by mohsen-gis** [jupyterhub/binderhub#1496]
### Bug description

I am trying to launch my repository on BinderHub, but I'm getting an error that says" RuntimeError: No space left on device: 'cache'"  and then says "Failed to connect to event stream."
The point is that I had previously launched the same repo multiple times with the very same environment.yml file. 

This is the link I am using to launch my repo: 
https://mybinder.org/v2/gh/mohsen-gis/lessons/master?filepath=beginner-lessons/big-data/bigdata-2.ipynb 

```
Step 40/53 : RUN TIMEFORMAT='time: %3R' bash -c 'time ${MAMBA_EXE} env update -p ${NB_PYTHON_PREFIX} --file "environment.yml" && time ${MAMBA_EXE} clean --all -f -y && ${MAMBA_EXE} list -p ${NB_PYTHON_PREFIX} '
 ---> Running in ed520e4e06f1

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/srv/conda/lib/python3.10/site-packages/conda/exceptions.py", line 1080, in __call__
        return func(*args, **kwargs)
      File "/srv/conda/lib/python3.10/site-packages/conda_env/cli/main.py", line 80, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/srv/conda/lib/python3.10/site-packages/conda_env/cli/main_update.py", line 123, in execute
        result[installer_type] = installer.install(prefix, specs, args, env)
      File "/srv/conda/lib/python3.10/site-packages/mamba/mamba_env.py", line 45, in mamba_install
        index = load_channels(pool, channel_urls, repos, prepend=False)
      File "/srv/conda/lib/python3.10/site-packages/mamba/utils.py", line 122, in load_channels
        index = get_index(
      File "/srv/conda/lib/python3.10/site-packages/mamba/utils.py", line 78, in get_index
        api.create_cache_dir(str(pkgs_dirs.first_writable_path))
    RuntimeError: No space left on device: 'cache'

`$ /srv/conda/bin/mamba update -p /srv/conda/envs/notebook --file environment.yml`

  environment variables:
                 CIO_TEST=<not set>
  CONDA_AUTO_UPDATE_CONDA=false
        CONDA_DEFAULT_ENV=/srv/conda/envs/notebook
                CONDA_DIR=/srv/conda
               CONDA_ROOT=/srv/conda
           CURL_CA_BUNDLE=<not set>
                     PATH=/home/jovyan/.local/bin:/home/jovyan/.local/bin:/srv/conda/envs/notebo
                          ok/bin:/srv/conda/bin:/srv/npm/bin:/usr/local/sbin:/usr/local/bin:/usr
                          /sbin:/usr/bin:/sbin:/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
       user config file : /home/jovyan/.condarc
 populated config files : /srv/conda/.condarc
          conda version : 4.11.0
    conda-build version : not installed
         python version : 3.10.4.final.0
       virtual packages : __linux=5.4.170=0
                          __glibc=2.27=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /srv/conda  (writable)
      conda av data dir : /srv/conda/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /srv/conda/pkgs
                          /home/jovyan/.conda/pkgs
       envs directories : /srv/conda/envs
                          /home/jovyan/.conda/envs
               platform : linux-64
             user-agent : conda/4.11.0 requests/2.27.1 CPython/3.10.4 Linux/5.4.170+ ubuntu/18.04.6 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

time: 0.561
Removing intermediate container ed520e4e06f1
The command '/bin/sh -c TIMEFORMAT='time: %3R' bash -c 'time ${MAMBA_EXE} env update -p ${NB_PYTHON_PREFIX} --file "environment.yml" && time ${MAMBA_EXE} clean --all -f -y && ${MAMBA_EXE} list -p ${NB_PYTHON_PREFIX} '' returned a non-zero code: 1Built image, launching...
Failed to connect to event stream
```

**Comment by consideRatio** [comment]
You must have arrived at a comoutational node that was unhealthy on the service mybinder.org, running binderhub software.

Unsure what can be done overall, transferring this issue to mybinder.org-deploy repo.
