### ISSUE TITLE
Deployment problem (Google Cloud) : Internal Server Error

### ISSUE THREAD

**Issue by nicain** [jupyterhub/binderhub#415]
Binderhub deployed on Google cloud, running into some issue

`kubectl --namespace=binder logs <binderhub-deployment-*>` reports:

```
[I 180115 18:37:44 app:269] BinderHub starting on port 8585
[I 180115 18:38:34 web:2063] 304 GET / (10.36.0.1) 28.11ms
[E 180115 18:39:32 web:1590] Uncaught exception GET /build/gh/nicain/hello-world.git/master (10.36.0.1)
    HTTPServerRequest(protocol='http', host='35.202.206.223', method='GET', uri='/build/gh/nicain/hello-world.git/master', version='HTTP/1.1', remote_ip='10.36.0.1', headers={'Host': '35.202.206.223', 'Connection': 'keep-alive', 'Accept': 'text/event-stream', 'Cache-Control': 'no-cache', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36', 'Referer': 'http://35.202.206.223/v2/gh/nicain/hello-world.git/master?filepath=helloworld.ipynb', 'Accept-Encoding': 'gzip, deflate', 'Accept-Language': 'en-US,en;q=0.9'})
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/site-packages/tornado/web.py", line 1511, in _execute
        result = yield result
      File "/usr/local/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
        value = future.result()
      File "/usr/local/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 4, in raise_exc_info
      File "/usr/local/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
        yielded = self.gen.throw(*exc_info)
      File "<string>", line 6, in _wrap_awaitable
      File "/usr/local/lib/python3.6/site-packages/binderhub/builder.py", line 170, in get
        image_manifest = await self.registry.get_image_manifest(*image_name.split('/', 1)[1].split(':', 1))
      File "<string>", line 3, in __await__
      File "/usr/local/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
        value = future.result()
      File "/usr/local/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 4, in raise_exc_info
      File "/usr/local/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
        yielded = self.gen.throw(*exc_info)
      File "/usr/local/lib/python3.6/site-packages/binderhub/registry.py", line 38, in get_image_manifest
        auth_resp = yield client.fetch(auth_req)
      File "/usr/local/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
        value = future.result()
      File "/usr/local/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 4, in raise_exc_info
    tornado.httpclient.HTTPError: HTTP 400: Bad Request
[I 180115 18:39:32 web:2063] 200 GET /build/gh/nicain/hello-world.git/master (10.36.0.1) 271.47ms
```

config.yaml:

```
hub:
  url: http://130.211.222.80
jupyterhub:
  hub:
    rbac:
      enabled: false
rbac:
  enabled: false
registry:
  enabled: true
  prefix: gcr.io/reliable-cairn-192018/dev
```

secret.yaml:

```
hub:
  services:
    binder:
      apiToken: <token1, redacted>
jupyterhub:
  hub:
    services:
      binder:
        apiToken: <token1, redacted>
  proxy:
    secretToken: <token2, redacted>
registry:
  password: '|{"private_key": "-----BEGIN PRIVATE KEY-----\n ... <redacted>
```

@choldgraf

**Comment by nicain** [comment]
Offline comment from @choldgraf:

> That looks to me like you don't have kubernetes and /or Docker running locally. Did you start them?

Kubernetes, I think so.  Docker, I don't remember starting that.  Can you point me to the location in the docs on how to do that?

**Comment by nicain** [comment]
http://35.202.206.223/v2/gh/nicain/helloworld/master?filepath=helloworld.ipynb

**Comment by nicain** [comment]
Also, when I try to go to my JupyterHub IP, I get 403: Forbidden; not sure this is the intended behavior.

**Comment by nicain** [comment]
The scripts I use to bring up the cluster are at https://github.com/nicain/binder-deploy

```
./setup.sh
./deploy.sh
```

**Comment by choldgraf** [comment]
Just looking through your scripts now, and I can't immediately see what could be going wrong. I didn't realize you were running this on google cloud already, so the kubernetes/docker questions aren't relevant.

Do you think we can hold off on getting this deploy working until we can get https://github.com/jupyterhub/binderhub/issues/402 worked out? Those will change the installation instructions a fair bit. It won't be a ton of work to adapt your cookiecutter (which is totally awesome, btw...we should definitely link to it from the docs) but we'll want to test out your deployment with this version of the instructions anyway. What do you think?

**Comment by nicain** [comment]
This should be fine, thanks.

**Comment by choldgraf** [comment]
Let's keep this open so that we can re-address this once I get the instructions updated, sound good?

**Comment by choldgraf** [comment]
hey @nicain - we took a pass at updating the instructions in #402 - the current version should have the RBAC problems fixed and should work with google cloud...wanna give a deployment another shot? Happy to help spot-check and/or send updates to the cookiecutter as well. LMK!
