### ISSUE TITLE
Image cleaner error on deploy

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/binderhub#528]
We just deployed the image cleaner, and promptly ran into the following error in the logs:

```
kubectl logs prod-dind-8wqqq image-cleaner
Pruning docker images when /var/lib/docker has less than 0.8% inodes free
Traceback (most recent call last):
  File "/usr/local/bin/image-cleaner.py", line 68, in <module>
    main()
  File "/usr/local/bin/image-cleaner.py", line 50, in main
    client = docker.from_env()
  File "/usr/local/lib/python3.6/site-packages/docker/client.py", line 27, in from_env
    return Client.from_env(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/docker/client.py", line 112, in from_env
    return cls(version=version, **kwargs_from_env(**kwargs))
  File "/usr/local/lib/python3.6/site-packages/docker/client.py", line 59, in __init__
    base_url, constants.IS_WINDOWS_PLATFORM, tls=bool(tls)
  File "/usr/local/lib/python3.6/site-packages/docker/utils/utils.py", line 438, in parse_host
    "Bind address needs a port: {0}".format(addr))
docker.errors.DockerException: Bind address needs a port: /var/run/dind/docker.sock
```

We've reverted this, so we should spot-check the issue so we can deploy a new binderhub!

cc @yuvipanda

**Comment by minrk** [comment]
I'm guessing it needs to be `unix:///var/run/...`

I think this bug snuck through because the docker client isn't created until the inodes are exhausted.

**Comment by alpha-nome** [comment]
Hi. I'm still getting this error. I tried the latest version of install --version=0.2.0-n221.h1875bcb. Still stuck on the creating container for binder-image-cleaner pod.
