### ISSUE TITLE
HTTP 403: Forbidden -- failure in get_image_manifest 

### ISSUE THREAD

**Issue by jhamman** [jupyterhub/binderhub#620]
I'm working on a new deployment of binderhub on GCP. Eventually there will be some custom configurations in the jupyterhub config sections but none of that is active for this deployment. Specifics, minus the secret configs, are available in this repository: https://github.com/jhamman/pangeo_binder

The link below is an example binder link that works on mybinder.org but not on my deployment.

http://35.185.197.178/v2/gh/dask/dask-examples/master

This yields a build log of

```
Internal Server Error
```

I'm wondering if someone can help decode the meaning of this error and point me in a better direction. I've already tried recreating the GCR service account once or twice.

*Note: this is the helm chart of binder version v0.1.0-795801e*

```
$ kubectl logs binder-6f46b7584c-8wzsh --namespace pangeo-binder

[E 180721 05:06:47 web:1591] Uncaught exception GET /build/gh/dask/dask-examples/master (10.138.0.3)
    HTTPServerRequest(protocol='http', host='35.185.197.178', method='GET', uri='/build/gh/dask/dask-examples/master', version='HTTP/1.1', remote_ip='10.138.0.3', headers={'Host': '35.185.197.178', 'Connection': 'keep-alive', 'Accept': 'text/event-stream', 'Cache-Control': 'no-cache', 'Dnt': '1', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36', 'Referer': 'http://35.185.197.178/', 'Accept-Encoding': 'gzip, deflate', 'Accept-Language': 'en-US,en;q=0.9'})
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/site-packages/tornado/web.py", line 1512, in _execute
        result = yield result
      File "/usr/local/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
        value = future.result()
      File "/usr/local/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 4, in raise_exc_info
      File "/usr/local/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
        yielded = self.gen.throw(*exc_info)
      File "<string>", line 6, in _wrap_awaitable
      File "/usr/local/lib/python3.6/site-packages/binderhub/builder.py", line 250, in get
        image_manifest = await self.registry.get_image_manifest(*'/'.join(image_name.split('/')[-2:]).split(':', 1))
      File "<string>", line 3, in __await__
      File "/usr/local/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
        value = future.result()
      File "/usr/local/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 4, in raise_exc_info
      File "/usr/local/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
        yielded = self.gen.throw(*exc_info)
      File "/usr/local/lib/python3.6/site-packages/binderhub/registry.py", line 42, in get_image_manifest
        resp = yield client.fetch(req)
      File "/usr/local/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
        value = future.result()
      File "/usr/local/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 4, in raise_exc_info
    tornado.httpclient.HTTPError: HTTP 403: Forbidden
```

**Comment by betatim** [comment]
This looks like a similar issue as https://github.com/jupyterhub/binderhub/issues/611

**Comment by jhamman** [comment]
Recreating my registry and redeploying without any comments in my configs seems to have fixed the problem. Thanks @betatim!
