### ISSUE TITLE
AWS Run time issue when launching sample binder server: Internal Server Error

### ISSUE THREAD

**Issue by andrewcheny** [jupyterhub/binderhub#631]
When trying to launch a sample binder it runs into error at the last stage (tried two sample binders same results):

Built image, launching ...
Launching server ...
Internal Server Error

Here is the log from binder pod:

andrew@hp:~/bh$ kubectl --namespace dev logs binder-66b9bd76cc-fgnw4
[I 180809 20:10:28 app:367] BinderHub starting on port 8585
[I 180809 20:12:27 web:2064] 200 GET / (192.168.74.156) 21.01ms
[I 180809 20:12:30 web:2064] 200 GET /static/dist/bundle.js?v=fccc0a55a818a2203a45bcf2a600490f (192.168.74.156) 40.77ms
[I 180809 20:12:34 web:2064] 200 GET /static/dist/styles.css?v=29c46cc42adc69240d63a4ffa7455fd4 (192.168.74.156) 13.79ms
[I 180809 20:12:59 web:2064] 200 GET /static/logo.svg?v=f9f0d927b67cc9dc99d788c822ca21c0 (192.168.74.156) 0.95ms
[I 180809 20:12:59 web:2064] 200 GET /static/images/badge.svg?v=a91770fb1255ac9f9e6cd6f5a92b5d17 (192.168.74.156) 0.67ms
[I 180809 20:12:59 web:2064] 200 GET /static/images/copy-icon-black.svg?v=2b8143bdaefdc425fbf8293cd1d76843 (192.168.74.156) 0.71ms
[I 180809 20:12:59 web:2064] 200 GET /static/images/markdown-icon.svg?v=4e4923577a5e538ad262509d8c569fa3 (192.168.74.156) 0.87ms
[I 180809 20:12:59 web:2064] 200 GET /static/dist/a493884b8da5e40a49761e45e26632b7.woff (192.168.74.156) 4.81ms
[I 180809 20:13:00 web:2064] 200 GET /static/images/rst-icon.svg?v=39f5db3a54755fe734e5311bd6288c5c (192.168.74.156) 0.87ms
[I 180809 20:13:00 web:2064] 200 GET /static/dist/448c34a56d699c29117adc64c43affeb.woff2 (192.168.74.156) 0.96ms
[I 180809 20:13:00 web:2064] 200 GET /static/dist/cc10b51ebde2156baf4012fbc9b3a0c1.woff (192.168.74.156) 1.13ms
[I 180809 20:13:00 web:2064] 200 GET /static/dist/4cf6f681b05ddc6375e51c804a496fe2.woff (192.168.74.156) 3.92ms
[I 180809 20:13:14 web:2064] 200 GET /static/favicon.ico?v=7102bb857703a0fece6d039a6777fc3f (192.168.74.156) 0.90ms
[I 180809 20:13:14 web:2064] 200 GET /static/favicon.ico?v=7102bb857703a0fece6d039a6777fc3f (192.168.74.156) 0.89ms
[I 180809 20:13:45 web:2064] 200 GET /favicon_building.ico (192.168.74.156) 0.85ms
[I 180809 20:13:45 web:2064] 200 GET /favicon_building.ico (192.168.74.156) 0.87ms
[I 180809 20:14:35 launcher:84] Creating user andrewcheny-r-6lhphyy3 for image gcr.io/alohak8t/bhandrewcheny-r:9a4bdc0322d32c1aba58eb90253f4fed2594da5b
2018-08-09 20:14:35,802 WARNING Connection pool is full, discarding connection: 10.100.0.1
[W 180809 20:14:35 connectionpool:277] Connection pool is full, discarding connection: 10.100.0.1
[E 180809 20:14:35 web:1591] Uncaught exception GET /build/gh/andrewcheny/r/master (192.168.74.156)
    HTTPServerRequest(protocol='http', host='ad84301629c0911e8b4d20e32ad42cf0-381476980.us-east-1.elb.amazonaws.com', method='GET', uri='/build/gh/andrewcheny/r/master', version='HTTP/1.1', remote_ip='192.168.74.156', headers={'Host': 'ad84301629c0911e8b4d20e32ad42cf0-381476980.us-east-1.elb.amazonaws.com', 'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0', 'Accept': 'text/event-stream', 'Accept-Language': 'en-GB,en;q=0.5', 'Accept-Encoding': 'gzip, deflate', 'Referer': 'http://ad84301629c0911e8b4d20e32ad42cf0-381476980.us-east-1.elb.amazonaws.com/v2/gh/andrewcheny/r/master?filepath=index.ipynb', 'Connection': 'keep-alive', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache'})
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/site-packages/tornado/web.py", line 1512, in _execute
        result = yield result
      File "/usr/local/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
        value = future.result()
      File "/usr/local/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 4, in raise_exc_info
      File "/usr/local/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
        yielded = self.gen.throw(*exc_info)
      File "<string>", line 6, in _wrap_awaitable
      File "/usr/local/lib/python3.6/site-packages/binderhub/builder.py", line 315, in get
        await self.launch()
      File "/usr/local/lib/python3.6/site-packages/binderhub/builder.py", line 338, in launch
        server_info = await launcher.launch(image=self.image_name, username=username)
      File "/usr/local/lib/python3.6/site-packages/binderhub/launcher.py", line 86, in launch
        await self.api_request('users/%s' % username, body=b'', method='POST')
      File "/usr/local/lib/python3.6/site-packages/binderhub/launcher.py", line 39, in api_request
        resp = await AsyncHTTPClient().fetch(req)
      File "<string>", line 3, in __await__
      File "/usr/local/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
        value = future.result()
      File "/usr/local/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 4, in raise_exc_info
      File "/usr/local/lib/python3.6/site-packages/tornado/stack_context.py", line 316, in wrapped
        ret = fn(*args, **kwargs)
      File "/usr/local/lib/python3.6/site-packages/tornado/gen.py", line 289, in <lambda>
        future, lambda future: callback(future.result()))
      File "/usr/local/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 4, in raise_exc_info
      File "/usr/local/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
        yielded = self.gen.throw(*exc_info)
      File "/usr/local/lib/python3.6/site-packages/tornado/tcpclient.py", line 177, in connect
        addrinfo = yield self.resolver.resolve(host, port, af)
      File "/usr/local/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
        value = future.result()
      File "/usr/local/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 4, in raise_exc_info
      File "/usr/local/lib/python3.6/site-packages/tornado/concurrent.py", line 363, in submit
        future.set_result(fn(*args, **kwargs))
      File "/usr/local/lib/python3.6/site-packages/tornado/netutil.py", line 391, in resolve
        addrinfo = socket.getaddrinfo(host, port, family, socket.SOCK_STREAM)
      File "/usr/local/lib/python3.6/socket.py", line 745, in getaddrinfo
        for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
    socket.gaierror: [Errno -2] Name or service not known
[I 180809 20:14:35 web:2064] 200 GET /build/gh/andrewcheny/r/master (192.168.74.156) 50235.05ms
[I 180809 20:14:36 web:2064] 200 GET /favicon_fail.ico (192.168.74.156) 0.91ms
[I 180809 20:14:36 web:2064] 200 GET /favicon_fail.ico (192.168.74.156) 0.64ms
2018-08-09 20:14:39,723 WARNING Connection pool is full, discarding connection: 10.100.0.1
[W 180809 20:14:39 connectionpool:277] Connection pool is full, discarding connection: 10.100.0.1
2018-08-09 20:22:21,822 WARNING Connection pool is full, discarding connection: 10.100.0.1
[W 180809 20:22:21 connectionpool:277] Connection pool is full, discarding connection: 10.100.0.1
[I 180809 20:22:21 launcher:84] Creating user andrewcheny-jupyter-extension-o4xn3apr for image gcr.io/alohak8t/bhandrewcheny-jupyter-extension:00c9a3ae01ef7e7e77ce986b0561149de69b7d66
[E 180809 20:22:21 web:1591] Uncaught exception GET /build/gh/andrewcheny/jupyter-extension/master (192.168.74.156)
    HTTPServerRequest(protocol='http', host='ad84301629c0911e8b4d20e32ad42cf0-381476980.us-east-1.elb.amazonaws.com', method='GET', uri='/build/gh/andrewcheny/jupyter-extension/master', version='HTTP/1.1', remote_ip='192.168.74.156', headers={'Host': 'ad84301629c0911e8b4d20e32ad42cf0-381476980.us-east-1.elb.amazonaws.com', 'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0', 'Accept': 'text/event-stream', 'Accept-Language': 'en-GB,en;q=0.5', 'Accept-Encoding': 'gzip, deflate', 'Referer': 'http://ad84301629c0911e8b4d20e32ad42cf0-381476980.us-east-1.elb.amazonaws.com/v2/gh/andrewcheny/jupyter-extension/master?filepath=index.ipynb', 'Connection': 'keep-alive', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache'})
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/site-packages/tornado/web.py", line 1512, in _execute
        result = yield result
      File "/usr/local/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
        value = future.result()
      File "/usr/local/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 4, in raise_exc_info
      File "/usr/local/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
        yielded = self.gen.throw(*exc_info)
      File "<string>", line 6, in _wrap_awaitable
      File "/usr/local/lib/python3.6/site-packages/binderhub/builder.py", line 315, in get
        await self.launch()
      File "/usr/local/lib/python3.6/site-packages/binderhub/builder.py", line 338, in launch
        server_info = await launcher.launch(image=self.image_name, username=username)
      File "/usr/local/lib/python3.6/site-packages/binderhub/launcher.py", line 86, in launch
        await self.api_request('users/%s' % username, body=b'', method='POST')
      File "/usr/local/lib/python3.6/site-packages/binderhub/launcher.py", line 39, in api_request
        resp = await AsyncHTTPClient().fetch(req)
      File "<string>", line 3, in __await__
      File "/usr/local/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
        value = future.result()
      File "/usr/local/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 4, in raise_exc_info
      File "/usr/local/lib/python3.6/site-packages/tornado/stack_context.py", line 316, in wrapped
        ret = fn(*args, **kwargs)
      File "/usr/local/lib/python3.6/site-packages/tornado/gen.py", line 289, in <lambda>
        future, lambda future: callback(future.result()))
      File "/usr/local/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 4, in raise_exc_info
      File "/usr/local/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
        yielded = self.gen.throw(*exc_info)
      File "/usr/local/lib/python3.6/site-packages/tornado/tcpclient.py", line 177, in connect
        addrinfo = yield self.resolver.resolve(host, port, af)
      File "/usr/local/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
        value = future.result()
      File "/usr/local/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 4, in raise_exc_info
      File "/usr/local/lib/python3.6/site-packages/tornado/concurrent.py", line 363, in submit
        future.set_result(fn(*args, **kwargs))
      File "/usr/local/lib/python3.6/site-packages/tornado/netutil.py", line 391, in resolve
        addrinfo = socket.getaddrinfo(host, port, family, socket.SOCK_STREAM)
      File "/usr/local/lib/python3.6/socket.py", line 745, in getaddrinfo
        for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
    socket.gaierror: [Errno -2] Name or service not known
[I 180809 20:22:21 web:2064] 200 GET /build/gh/andrewcheny/jupyter-extension/master (192.168.74.156) 166666.87ms
2018-08-09 20:22:22,595 WARNING Connection pool is full, discarding connection: 10.100.0.1
[W 180809 20:22:22 connectionpool:277] Connection pool is full, discarding connection: 10.100.0.1

**Comment by betatim** [comment]
It sounds like there is a DNS/networking problem as it can't resolve the hostname of the hub pod.

` await self.api_request('users/%s' % username, body=b'', method='POST')` this line makes a call to the jupyterhub.

To confirm and debug the networking issue I'd `kubectl exec -it ...` into the binder pod and try to manually connect to the jupyterhub pod and vice versa.

**Comment by manics** [comment]
Hi :wave: This is an old issue which doesn't sound like a BinderHub bug so I'm closing it. If you have more questions please use the [Jupyter community forum https://discourse.jupyter.org/](https://discourse.jupyter.org/).
