### ISSUE TITLE
Kubernetes binderhub launches containers with incorrect resources requests

### ISSUE THREAD

**Issue by george-miller** [jupyterhub/binderhub#756]
I am using Kubernetes on AWS EKS, and I tried to use helm to deploy binderhub.  My values yml looks like this:

```
pdb:
  enabled: true
  minAvailable: 1

replicas: 1

resources:
  requests:
    cpu: 0.2
    memory: 512Mi
  limits:
    cpu: 0.2
    memory: 512Mi

rbac:
  enabled: true

nodeSelector: {}

image:
  name: jupyterhub/k8s-binderhub
  tag: 58e8ae9


service:
  type: ClusterIP
  labels: {}
  annotations:
    prometheus.io/scrape: 'true'
  nodePort:


registry:
  url: "https://index.docker.io/v1"
  username: <name>
  password: <pass>

config:
  BinderHub:
    use_registry: true
    image_prefix:<name>/binder
  DockerRegistry:
    url: "https://registry.hub.docker.com" # the actual v2 registry url
    auth_config_url: "https://index.docker.io/v1" # must match above!
    token_url: "https://auth.docker.io/token?service=registry.docker.io"

extraConfig: {}

# have to set cors.allowOrigin twice:
# once in top-level cors.allowOrigin,
# and again in jupyterhub.hub.extraConfigMap.cors.allowOrigin

# Using YAML anchors, `&cors` for the first appearance and `*cors` for subsequent
# appearances, allows us to remove redundancy in this (BinderHub) `values.yaml`.
# The anchors do not extend beyond this file.
# As such, users must set `cors` separately for their own user `values.yaml` for notebooks.
# `cors` will be set separately in the user `values.yaml` and binderhub`values.yaml`.
# The same anchor pattern (`&cors`, `*cors`) can be used in the user `values.yaml`.

cors: &cors
  allowOrigin:

jupyterhub:

  hub:
    extraConfig:
      binder: |
        import os
        import sys
        import yaml
        from tornado import web
        # get cors config from values.custom.cors
        import z2jh
        cors = z2jh.get_config('custom.cors', {})
        # image & token are set via spawn options
        from kubespawner import KubeSpawner
        class BinderSpawner(KubeSpawner):
          def get_args(self):
              args = [
                  '--ip=0.0.0.0',
                  '--port=%i' % self.port,
                  '--NotebookApp.base_url=%s' % self.server.base_url,
                  '--NotebookApp.token=%s' % self.user_options['token'],
                  '--NotebookApp.trust_xheaders=True',
              ]
              allow_origin = cors.get('allowOrigin')
              if allow_origin:
                  args.append('--NotebookApp.allow_origin=' + allow_origin)
              return args + self.args
          def start(self):
              if 'token' not in self.user_options:
                raise web.HTTPError(400, "token required")
              if 'image' not in self.user_options:
                raise web.HTTPError(400, "image required")
              self.image = self.user_options['image']
              return super().start()
        c.JupyterHub.spawner_class = BinderSpawner
    service:
      type: ClusterIP
    services:
      binder:
        admin: true
        apiToken: "<token>"
    deploymentStrategy:
      # sqlite-pvc backed hub requires Recreate strategy to work
      type: Recreate
      # This is required for upgrading to work
      rollingUpdate:
    db:
      type: sqlite-pvc
      pvc:
        accessModes:
          - ReadWriteOnce
        storage: 1Gi
        storageClassName: <default>
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 200m
        memory: 512Mi

  scheduling:
    userScheduler:
      resources:
        requests:
          cpu: 50m
          memory: 256Mi
        limits:
          cpu: 200m
          memory: 512Mi

  singleuser:
    cpu:
      limit: 1
      guarantee: 1
    memory:
      limit: 1G
      guarantee: 1G
    extraResource:
      limits: {}
      guarantees: {}

  proxy:
    secretToken: '<token>'
    https:
      enabled: true
      type: offload
    service:
      type: NodePort
    chp:
      resources:
        requests:
          cpu: 200m
          memory: 512Mi
        limits:
          cpu: 200m
          memory: 512Mi
    nginx:
      resources:
        requests:
          cpu: 200m
          memory: 512Mi
        limits:
          cpu: 200m
          memory: 512Mi
    lego:
      resources:
        requests:
          cpu: 200m
          memory: 512Mi
        limits:
          cpu: 200m
          memory: 512Mi
  ingress:
    enabled: true
    hosts: ["jupyterhub.<host>"]

deployment:
  labels: {}

dind:
  enabled: false
  initContainers: []
  daemonset:
    image:
      name: docker
      tag: 17.11.0-ce-dind
  storageDriver: overlay2
  resources: {}
  hostSocketDir: /var/run/dind
  hostLibDir: /var/lib/dind

imageCleaner:
  enabled: true
  image:
    name: jupyterhub/k8s-image-cleaner
    tag: c56fb9e
    repository: jupyterhub/k8s-image-cleaner
  # delete an image at most every 5 seconds
  delay: 5
  # when 80% of inodes are used,
  # cull images until it drops below 60%
  imageGCThresholdHigh: 80
  imageGCThresholdLow: 60
  # cull images on the host docker as well as dind
  host:
    enabled: true
    dockerSocket: /var/run/docker.sock
    dockerLibDir: /var/lib/docker

ingress:
  enabled: true
  https:
    enabled: false
    type: kube-lego
  hosts:
    - binderhub.<hostname>
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  tls: []
    # Secrets must be manually created in the namespace.
    # - secretName: chart-example-tls
    #   hosts:
    #     - chart-example.local

initContainers: []
extraVolumes: []
extraVolumeMounts: []

```

I had to put resource limits and requests everywhere because we are using a [LimitRange](https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/memory-default-namespace/) to specify default resources, and in some cases the default limits in the helm chart were less than the default requests in my LimitRange.

I was trying to deploy https://github.com/binder-examples/python2_with_3 this repo with binder as an example, and I was getting this error in the binder logs:

```
[E 181213 17:13:08 ioloop:792] Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x7fcac9c25bf8>, <Future at 0x7fcabd47a128 state=finished raised ApiException>)
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/site-packages/tornado/ioloop.py", line 759, in _run_callback
        ret = callback()
      File "/usr/local/lib/python3.6/site-packages/tornado/stack_context.py", line 276, in null_wrapper
        return fn(*args, **kwargs)
      File "/usr/local/lib/python3.6/site-packages/tornado/ioloop.py", line 780, in _discard_future_result
        future.result()
      File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 425, in result
        return self.__get_result()
      File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
        raise self._exception
      File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/usr/local/lib/python3.6/site-packages/binderhub/build.py", line 202, in submit
        ret = self.api.create_namespaced_pod(self.namespace, self.pod)
      File "/usr/local/lib/python3.6/site-packages/kubernetes/client/apis/core_v1_api.py", line 6057, in create_namespaced_pod
        (data) = self.create_namespaced_pod_with_http_info(namespace, body, **kwargs)
      File "/usr/local/lib/python3.6/site-packages/kubernetes/client/apis/core_v1_api.py", line 6142, in create_namespaced_pod_with_http_info
        collection_formats=collection_formats)
      File "/usr/local/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 321, in call_api
        _return_http_data_only, collection_formats, _preload_content, _request_timeout)
      File "/usr/local/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 155, in __call_api
        _request_timeout=_request_timeout)
      File "/usr/local/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 364, in request
        body=body)
      File "/usr/local/lib/python3.6/site-packages/kubernetes/client/rest.py", line 266, in POST
        body=body)
      File "/usr/local/lib/python3.6/site-packages/kubernetes/client/rest.py", line 222, in request
        raise ApiException(http_resp=r)
    kubernetes.client.rest.ApiException: (403)
    Reason: Forbidden
    HTTP response headers: HTTPHeaderDict({'Audit-Id': 'e236bbb2-23de-41fc-81d8-1d8000aa97f8', 'Content-Type': 'application/json', 'Date': 'Thu, 13 Dec 2018 17:13:08 GMT', 'Content-Length': '348'})
    HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods \"build-binder-2dexamples-2dr-5fwith-5fpython-c8dcd8-229e7e\" is forbidden: minimum memory usage per Container is 1Mi, but request is 0.","reason":"Forbidden","details":{"name":"build-binder-2dexamples-2dr-5fwith-5fpython-c8dcd8-229e7e","kind":"pods"},"code":403}
```

I looked around the code for KubeSpawner and found [this](https://github.com/jupyterhub/kubespawner/blob/master/kubespawner/spawner.py#L768) which looked promising so I tried adding this to BinderSpawner.start but it didn't seem to do anything:
```
self.extra_container_config = {"resources":{"requests":{"memory":"1Gi","cpu":"1"}, "limits":{"memory":"1Gi","cpu":"1"}}}
```

In general I just had a lot of trouble trying to get this running and I just heard that my team is actually going to go with another product that makes the need for binderhub/jupyterhub obsolete so we aren't going to try to run it anymore.  However, this still seems like a bug so I figured I'd let you guys know.

**Comment by manics** [comment]
Hi :wave: This is an old issue which no one else has reported so I'm closing it. If you have more questions please use the [Jupyter community forum https://discourse.jupyter.org/](https://discourse.jupyter.org/).
