### ISSUE TITLE
Binderhub install gives 400 error (bad request)

### ISSUE THREAD

**Issue by mbobra** [jupyterhub/binderhub#789]
Hello! I'm trying to install Binderhub v0.2.0-b593363 and I get a 400 error. I saw issue #611 about this, but I don't have any comments in starting with `<` that may be causing the error. This might be a silly mistake or oversight on my part, but I've tried to deploy the Binderhub more than once (including a tear-down and re-start) and I still get the error. Could someone help me with this? 

```
Traceback (most recent call last):
      File "/usr/local/lib/python3.6/site-packages/tornado/web.py", line 1543, in _execute
        result = yield result
      File "/usr/local/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
        value = future.result()
      File "/usr/local/lib/python3.6/site-packages/binderhub/builder.py", line 273, in get
        image_manifest = await self.registry.get_image_manifest(*'/'.join(image_name.split('/')[-2:]).split(':', 1))
      File "/usr/local/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run
        yielded = self.gen.throw(*exc_info)
      File "/usr/local/lib/python3.6/site-packages/binderhub/registry.py", line 199, in get_image_manifest
        auth_resp = yield client.fetch(auth_req)
      File "/usr/local/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
        value = future.result()
    tornado.httpclient.HTTPError: HTTP 400: Bad Request
```

cc @jmason86

**Comment by mbobra** [comment]
I posted this as a Binderhub topic on the [Jupyter discourse page](https://discourse.jupyter.org/t/binderhub-install-gives-400-error-bad-request/398) per @choldgraf 's advice so I'm closing this issue.

**Comment by choldgraf** [comment]
Ah I didn't notice you had opened an issue here, that is fine too :-) but let's see if the discourse post gets any traction
