### ISSUE TITLE
Can't install binderhub from PyPI

### ISSUE THREAD

**Issue by marnovo** [jupyterhub/binderhub#97]
Can't install binderhub via pip. When trying to install `binderhub` via `pip` from Python 3.6:

```bash
> pip install binderhub --verbose

Collecting binderhub
  1 location(s) to search for versions of binderhub:
  * https://pypi.python.org/simple/binderhub/
  Getting page https://pypi.python.org/simple/binderhub/
  Looking up "https://pypi.python.org/simple/binderhub/" in the cache
  No cache entry available
  Starting new HTTPS connection (1): pypi.python.org
  "GET /simple/binderhub/ HTTP/1.1" 404 38
  Status code 404 not in [200, 203, 300, 301]
  Could not fetch URL https://pypi.python.org/simple/binderhub/: 404 Client Error: Not Found (binderhub does not exist) for url: https://pypi.python.org/simple/binderhub/ - skipping
  Could not find a version that satisfies the requirement binderhub (from versions: )
Cleaning up...
No matching distribution found for binderhub
Exception information:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.6/site-packages/pip/commands/install.py", line 335, in run
    wb.build(autobuilding=True)
  File "/usr/local/lib/python3.6/site-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/local/lib/python3.6/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/local/lib/python3.6/site-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/usr/local/lib/python3.6/site-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/local/lib/python3.6/site-packages/pip/index.py", line 514, in find_requirement
    'No matching distribution found for %s' % req
pip.exceptions.DistributionNotFound: No matching distribution found for binderhub
```

**Comment by minrk** [comment]
We haven't made a release on PyPI yet, so you'll have to install it from the repo:

    pip install git+https://github.com/jupyterhub/binderhub

**Comment by marnovo** [comment]
Got it, thank you.
